<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Apply actions' => '',
  'Apply content spinning to all videos' => '',
  'Auto content spinning' => '',
  'Bulk Video Ftp Upload Step 1' => '',
  'Bulk Video Http Upload Step 2' => '',
  'Bulk Video Upload Step 3' => '',
  'Category' => '',
  'Choose at least one category' => '',
  'Could not get video information' => '',
  'Description' => '',
  'Download' => '',
  'Duration' => '',
  'Go to top' => '',
  'Grab' => '',
  'Grab all videos' => '',
  'Hotlink' => '',
  'Log out' => '',
  'Remove flag' => '',
  'Save' => '',
  'Search' => '',
  'Status' => '',
  'Submit' => '',
  'Success.' => '',
  'Tags' => '',
  'The title is required' => '',
  'The username is required' => '',
  'There is no crawler for the {website} website' => '',
  'There is no user with the username {username}' => '',
  'Title' => '',
  'Username' => '',
  'Video conversion or thumbnail extraction failed. Check log for more details.' => '',
  'Welcome' => '',
  'You must upload a video file or give the url of a video file' => '',
);
