<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '#' => '',
  'Activate' => '',
  'Advanced search' => '',
  'Allowed are lowercase letters and digits.' => '',
  'Create' => '',
  'Create new text setting' => '',
  'Create profile field' => '',
  'Create profile fields group' => '',
  'Display order of fields.' => '',
  'Display order of group.' => '',
  'Enter the activation code you recieved below.' => '',
  'Group name' => '',
  'group name' => '',
  'Group name on the language of "sourceLanguage".' => '',
  'If you failed to recieve the activation email, click the Resend Activation button.' => '',
  'Incorrect symbol\'s. (a-z)' => '',
  'Index' => '',
  'List profile field' => '',
  'Login' => '',
  'Manage' => '',
  'Manage profile fields' => '',
  'Manage profile fields groups' => '',
  'Manage text settings' => '',
  'Manage users' => '',
  'Position' => '',
  'Profile' => '',
  'Profile field {fieldname}' => '',
  'Profile fields' => '',
  'Profile fields groups' => '',
  'Profile of ' => '',
  'Resend Activation' => '',
  'Save' => '',
  'Search' => '',
  'Text settings' => '',
  'This field already exists.' => '',
  'Title' => '',
  'Update' => '',
  'Update profile field' => '',
  'Update profile fields group {group_name}' => '',
  'User administration panel' => '',
  'User list' => '',
  'Users' => '',
  'View profile fields group #{group_name}' => '',
  'Yum Text Settings' => '',
);
