<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Authorid' => 'Authorid',
  'Browser title' => 'Titre du navigateur',
  'Content' => 'Contenu',
  'Create' => 'Créer',
  'Create new sitecontent here' => 'Créer du nouveau contenu de site ici',
  'Create sitecontent' => 'Création de contenu de site',
  'Createtime' => 'Createtime',
  'Edit this sitecontent' => 'Editer le contenu du site',
  'Language' => 'Langue',
  'Manage Menustructure' => 'Gérer la structure du menu',
  'Manage Sitecontent' => 'Gérer le contenu du site',
  'No results found' => 'Pas de résultats trouvés',
  'Parent' => 'Parent',
  'Position' => 'Position',
  'Results:' => 'Résultats',
  'Save sitecontent' => 'Sauvegarder le contenu du site',
  'Search results' => 'Rechercher des résultats',
  'Sitecontent' => 'Contenu de site',
  'Title' => 'Titre',
  'URL title' => 'Titre url',
  'Update' => 'mise à jour',
  'Updatetime' => 'Heure de la mise à jour',
  'Welcome to your CMS' => 'Bienvenue dans votre CMS',
);
