<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '{attribute} is too long (max. {num} characters).' => '{attribute} est trop long (max. {num} caractères).',
  '{attribute} is too short (min. {num} characters).' => '{attribute} est trop courte (min. {num} caractères).',
  '{attribute} must include at least {num} digits.' => '{attribute} doit contenir au moins {num} chiffres.',
  '{attribute} must include at least {num} lower case letters.' => '{attribute} doit contenir au moins {num} minuscules.',
  '{attribute} must include at least {num} symbols.' => '{attribute} doit contenir au moins {num} symboles.',
  '{attribute} must include at least {num} upper case letters.' => '{attribute} doit contenir au moins {num} majuscules.',
  '{attribute} must not contain more than {num} sequentially repeated characters.' => '{attribute} ne peut pas contenir plus que {num} caractères répétés de manière séquentielle',
  '{attribute} must not contain whitespace.' => '{attribute} ne peut pas contenir des espaces.',
);
