<?php
class CountryChooser extends CWidget
{
	public $multiple = false;
	public $htmlOptions = array();
	public $field = 'country';
	public $value = '';
	public $flagPath = null;
	public $flagUrl = '';
	public $continents = array(
	'Europe', 
	'North America', 
	'South America', 
	'Asia', 
	'Australia', 

);
	public $countries = array(
			'Afghanistan',
			'African Union(OAS)',
			'Albania',
			'Algeria',
			'American Samoa',
			'Andorra',
			'Angola',
			'Anguilla',
			'Antarctica',
			'Antigua & Barbuda',
			'Arab League',
			'Argentina',
			'Armenia',
			'Aruba',
			'ASEAN',
			'Australia',
			'Austria',
			'Azerbaijan',
			'Bahamas',
			'Bahrain',
			'Bangladesh',
			'Barbados',
			'Belarus',
			'Belgium',
			'Belize',
			'Benin',
			'Bermuda',
			'Bhutan',
			'Bolivia',
			'Bosnia & Herzegovina',
			'Botswana',
			'Brazil',
			'Brunei',
			'Bulgaria',
			'Burkina Faso',
			'Burundi',
			'Cambodja',
			'Cameroon',
			'Canada',
			'Cape Verde',
			'CARICOM',
			'Cayman Islands',
			'Central African Republic',
			'Chad',
			'Chile',
			'China',
			'CIS',
			'Colombia',
			'Commonwealth',
			'Comoros',
			'Congo-Brazzaville',
			'Congo-Kinshasa(Zaire)',
			'Cook Islands',
			'Costa Rica',
			'Cote d\'Ivoire',
			'Croatia',
			'Cuba',
			'Cyprus',
			'Czech Republic',
			'Denmark',
			'Djibouti',
			'Dominican Republic',
			'Dominica',
			'Ecuador',
			'Egypt',
			'El Salvador',
			'England',
			'Equatorial Guinea',
			'Eritrea',
			'Estonia',
			'Ethiopia',
			'European Union',
			'Faroes',
			'Fiji',
			'Finland',
			'flags',
			'France',
			'Gabon',
			'Gambia',
			'Georgia',
			'Germany',
			'Ghana',
			'Gibraltar',
			'Greece',
			'Greenland',
			'Grenada',
			'Guadeloupe',
			'Guam',
			'Guatemala',
			'Guernsey',
			'Guinea-Bissau',
			'Guinea',
			'Guyana',
			'Haiti',
			'Honduras',
			'Hong Kong',
			'Hungary',
			'Iceland',
			'India',
			'Indonesia',
			'Iran',
			'Iraq',
			'Ireland',
			'Islamic Conference',
			'Isle of Man',
			'Israel',
			'Italy',
			'Jamaica',
			'Japan',
			'Jersey',
			'Jordan',
			'Kazakhstan',
			'Kenya',
			'Kiribati',
			'Kosovo',
			'Kuwait',
			'Kyrgyzstan',
			'Laos',
			'Latvia',
			'Lebanon',
			'Lesotho',
			'Liberia',
			'Libya',
			'Liechtenstein',
			'LIthuania',
			'Luxembourg',
			'Macao',
			'Macedonia',
			'Madagascar',
			'Malawi',
			'Malaysia',
			'Maldives',
			'Mali',
			'Malta',
			'Marshall Islands',
			'Martinique',
			'Mauritania',
			'Mauritius',
			'Mexico',
			'Micronesia',
			'Moldova',
			'Monaco',
			'Mongolia',
			'Montenegro',
			'Montserrat',
			'Morocco',
			'Mozambique',
			'Myanmar(Burma)',
			'Namibia',
			'NATO',
			'Nauru',
			'Nepal',
			'Netherlands Antilles',
			'Netherlands',
			'New Caledonia',
			'New Zealand',
			'Nicaragua',
			'Nigeria',
			'Niger',
			'Northern Cyprus',
			'Northern Ireland',
			'North Korea',
			'Norway',
			'Olimpic Movement',
			'Oman',
			'OPEC',
			'Pakistan',
			'Palau',
			'Palestine',
			'Panama',
			'Papua New Guinea',
			'Paraguay',
			'Peru',
			'Philippines',
			'Poland',
			'Portugal',
			'Puerto Rico',
			'Qatar',
			'Red Cross',
			'Reunion',
			'Romania',
			'Russian Federation',
			'Rwanda',
			'Saint Lucia',
			'Samoa',
			'San Marino',
			'Sao Tome & Principe',
			'Saudi Arabia',
			'Scotland',
			'Senegal',
			'Serbia(Yugoslavia)',
			'Seychelles',
			'Sierra Leone',
			'Singapore',
			'Slovakia',
			'Slovenia',
			'Solomon Islands',
			'Somalia',
			'Somaliland',
			'South Africa',
			'South Korea',
			'Spain',
			'Sri Lanka',
			'St Kitts & Nevis',
			'St Vincent & the Grenadines',
			'Sudan',
			'Suriname',
			'Swaziland',
			'Sweden',
			'Switzerland',
			'Syria',
			'Tahiti(French Polinesia)',
			'Taiwan',
			'Tajikistan',
			'Tanzania',
			'Thailand',
			'Timor-Leste',
			'Togo',
			'Tonga',
			'Trinidad & Tobago',
			'Tunisia',
			'Turkey',
			'Turkmenistan',
			'Turks and Caicos Islands',
			'Tuvalu',
			'Uganda',
			'Ukraine',
			'United Arab Emirates',
			'United Kingdom(Great Britain)',
			'United Nations',
			'United States of America (USA)',
			'Uruguay',
			'Uzbekistan',
			'Vanutau',
			'Vatican City',
			'Venezuela',
			'Viet Nam',
			'Virgin Islands British',
			'Virgin Islands US',
			'Wales',
			'Western Sahara',
			'Yemen',
			'Zambia',
			'Zimbabwe',
			);


	public function init() {
		if($this->flagPath === null)
			$this->flagPath = 'application.components.flags.32';

		$this->flagUrl = Yii::app()->assetManager->publish(
				Yii::getPathOfAlias($this->flagPath));
		parent::init();
	}

	public function run() {
		$this->render('select_country', array(
					'htmlOptions' => $this->htmlOptions,
					'field' => $this->field,
					'flagUrl' => $this->flagUrl,
					'value' => $this->value,
					'countries' => $this->countries,
					'continents' => $this->continents,
					'multiple' => $this->multiple));

		return parent::run();
	}
}
