<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Apply actions' => 'Appliquer l\'action',
  'Apply content spinning to all videos' => 'Appliquer le contenu spinné à toutes les vidéos',
  'Auto content spinning' => 'Contenu spinné automatique',
  'Bulk Video Ftp Upload Step 1' => 'Envoi massif de vidéos par Ftp - Etape 1',
  'Bulk Video Http Upload Step 2' => 'Envoi massif de vidéos par Http - Etape 2',
  'Bulk Video Upload Step 3' => 'Envoi massif de vidéos - Etape 3',
  'Category' => 'Catégorie',
  'Choose at least one category' => 'Choisissez au moins une catégorie',
  'Could not get video information' => 'Impossible d\'obtenir des informations vidéo',
  'Description' => 'Description',
  'Download' => 'Téléchargement',
  'Duration' => 'Durée',
  'Go to top' => 'Allez en haut',
  'Grab' => 'Grab',
  'Grab all videos' => 'Grab toutes les vidéos',
  'Hotlink' => 'Hotlink',
  'Log out' => 'Déconnecter',
  'Remove flag' => 'Enlever le drapeau',
  'Save' => 'Sauvegarder',
  'Search' => 'Rechercher',
  'Status' => 'Etat',
  'Submit' => 'Soumettre',
  'Success.' => 'Succès',
  'Tags' => 'Tags',
  'The title is required' => 'Le titre est requis',
  'The username is required' => 'Le nom d\'utilisateur est requis',
  'There is no crawler for the {website} website' => 'Il n\'y a pas de crawler pour le site web {website}',
  'There is no user with the username {username}' => 'Il n\'y a pas d\'utilisateur ayant pour nom {username}',
  'Title' => 'Titre',
  'Username' => 'Nom d\'utilisateur',
  'Video conversion or thumbnail extraction failed. Check log for more details.' => 'Conversion vidéo ou extraction de vignette a échoué. Vérifiez le log pour plus de détails',
  'Welcome' => 'Bienvenue',
  'You must upload a video file or give the url of a video file' => 'Vous devez télécharger un fichier vidéo ou indiquer l\'url du fichier vidéo',
);
