<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Error while trying to create folder structure {path}. Error occured while trying to create folder {workingPath}' => 'Une erreur est survenue lors de la création de la structure des dossiers {path}. Une erreur est survenue lors de la création du dossier {workingPath}',
  'No crawler found for this website' => 'Pas de crawler trouvé pour ce site web',
  'Stopped trying to create folder structure {path} because it was outsite of video thumbs base path {basePath}' => 'La création de la structure du dossier {path} a été arrêter parce qu\'elle se trouve en-dehors du chemin de base des vignettes de vidéos {basePath}',
);
