<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '#' => '#',
  'Activate' => 'Activer',
  'Advanced search' => 'Recherche avancée',
  'Allowed are lowercase letters and digits.' => 'Seuls les caractères en minuscules et les chiffres sont admis.',
  'Create' => 'Créer',
  'Create new text setting' => 'Créer des nouveaux réglages texte',
  'Create profile field' => 'Créer un champ de profil',
  'Create profile fields group' => 'Créer un groupe de champs de profil',
  'Display order of fields.' => 'Afficher l\'ordre des champs',
  'Display order of group.' => 'Afficher l\'ordre du groupe',
  'Enter the activation code you recieved below.' => 'Entrez le code d\'activation que vous avez reçu ci-dessous.',
  'Group name' => 'Nom du groupe',
  'group name' => 'nom du groupe',
  'Group name on the language of "sourceLanguage".' => 'Regroupez les noms selon la langue de "sourceLanguage" ',
  'If you failed to recieve the activation email, click the Resend Activation button.' => 'Si vous n\'avez pas reçu l\'email d\'activation, veuillez utiliser le bouton Renvoyer l\'activation.',
  'Incorrect symbol\'s. (a-z)' => 'Symboles incorrects. (a-z)',
  'Index' => 'Index',
  'List profile field' => 'Lister les champs de profile',
  'Login' => 'Connexion',
  'Manage' => 'Gérer',
  'Manage profile fields' => 'Gérer les champs de profile',
  'Manage profile fields groups' => 'Gérer les groupes de champs de profil',
  'Manage text settings' => 'Gérer les réglages texte',
  'Manage users' => 'Gérer les utilisateurs',
  'Position' => 'Position',
  'Profile' => 'Profile',
  'Profile field {fieldname}' => 'Champ de profile {fieldname}',
  'Profile fields' => 'Champs de profil',
  'Profile fields groups' => 'Groupes de champs de profile',
  'Profile of ' => 'Profile de ',
  'Resend Activation' => 'Renvoyer l\'Activation ',
  'Save' => 'Sauvegarder',
  'Search' => 'Rechercher',
  'Text settings' => 'Réglages texte',
  'This field already exists.' => 'Ce champ existe déjà',
  'Title' => 'Titre',
  'Update' => 'Mettre à jour',
  'Update profile field' => 'Mise à jour du champ profile',
  'Update profile fields group {group_name}' => 'Mise à jour des groupes de champs de profile {group_name}',
  'User administration panel' => 'Panneau d\'administration des utilisateurs',
  'User list' => 'Liste des utilisateurs ',
  'Users' => 'Utilisateurs',
  'View profile fields group #{group_name}' => 'Voir les groupe des champs de profile #{group_name}',
  'Yum Text Settings' => 'Réglages de texte Yum',
);
